<?php
/**
 * Created by PhpStorm.
 * User: boxer
 * Date: 3/5/2018
 * Time: 23:40
 */

namespace app\lib\exception;


use Exception;
use think\exception\Handle;

class ExceptionHandler extends Handle
{
    public function render(Exception $e)
    {
        return parent::render($e); // TODO: Change the autogenerated stub
    }
}